# Generated by Django 3.0.6 on 2020-06-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('surface', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('historique', models.TextField()),
                ('ressources', models.TextField()),
                ('personnalités', models.TextField()),
                ('drapeau', models.ImageField(upload_to='media')),
                ('hymne', models.FileField(upload_to='media')),
            ],
        ),
    ]
