# Generated by Django 3.0.6 on 2020-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.FloatField(),
        ),
    ]
