# Generated by Django 3.0.6 on 2020-06-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200616_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='drapeau_carre',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
