# Generated by Django 3.0.6 on 2020-06-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20200617_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowimages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Vedios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedio', models.FileField(upload_to='vedios')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
        ),
    ]
